version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: morningbox-app
    tty: true
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
